language: python

env:
  global:
  # code climate test-reporter token
    - CC_TEST_REPORTER_ID=9a90edf9d2b92f5171dc75efb10af3aaa616cf5d76d96152e2b4624a46e0f11e
python:
  - 3.6

  - pip install
  - pip install -r requirements.txt

services:
  - postgresql

script:
  - nosetests --with-coverage

before_script:
  - psql -c "CREATE DATABASE test_yummy_recipes;" -U postgres
  - psql -c "ALTER USER postgres WITH PASSWORD 'mypassword';" -U postgres
  # getting code climate test reporter
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

after_success:
  - coveralls

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT