language: python

python:
  - 3.6

  - pip install
  - pip install -r requirements.txt

before_script:
  - python migrate.py db init
  - python migrate.py db migrate
  - python migrate.py db upgrade

script:
  - python tests.py