language: python

env:
  global:
  - YUMMY_DATABASE_URI=postgresql://postgres:mypassword@127.0.0.1:5432/yummy_recipes
  - YUMMY_SECRET_KEY="The secret key you prefer"
python:
  - 3.6

  - pip install
  - pip install -r requirements.txt

services:
  - postgresql

script:
  - nosetests --with-coverage

before_script:
  - psql -c "CREATE DATABASE test_yummy_recipes;" -U postgres
  - psql -c "ALTER USER postgres WITH PASSWORD 'mypassword';" -U postgres

after_success:
  - coveralls
