language: python

python:
  - 3.6

  - pip install
  - pip install -r requirements.txt

services:
  - postgresql

script:
  - python tests.py

before_script:
  - psql -c "CREATE DATABASE test_yummy_recipes;" -U postgres
  - psql -c "ALTER USER postgres WITH PASSWORD 'mypassword';" -U postgres